---
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  advanced:
    retentionResolutionRaw: 2d
    retentionResolution5m: 7d
    retentionResolution1h: 30d
