---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acs-operator
  namespace: rhacs-operator
spec:
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
