---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

generatorOptions:
  disableNameSuffixHash: true
  labels:
    cluster.open-cluster-management.io/credentials: ""
    cluster.open-cluster-management.io/type: gcp

secretGenerator:
  - name: gcp-creds
    envs:
      - secrets/.env.gcp
    files:
      - secrets/additionalTrustBundle
      - secrets/baseDomain
      - secrets/osServiceAccount.json