---
apiVersion: v1
metadata:
  name: demo
baseDomain: lab.bewley.net
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
  platform:
    vsphere:
      cpus: 12
      coresPerSocket:  1
      memoryMB: 32768
      osDisk:
        diskSizeGB: 100
compute:
  - hyperthreading: Enabled
    name: worker
    platform: {}
      # vsphere:
      #   cpus: 6
      #   coresPerSocket: 2
      #   memoryMB: 24552
      #   osDisk:
      #     diskSizeGB: 80
    replicas: 0
platform:
  vsphere:
    apiVIP: 192.168.4.15
    ingressVIP: 192.168.4.14
    network: lab-192-168-4-0-b24
    datacenter: Garden
    cluster: Goat
    defaultDatastore: VMData-HD
    vCenter: vcenter.lab.bewley.net
    # https://bugzilla.redhat.com/show_bug.cgi?id=1996188
    password: EXAMPLE
    username: administrator@vcenter.lab.bewley.net
pullSecret: "" # skip, hive will inject based on it's secrets
