= Red Hat Advanced Cluster Management for Kubernetes Demonstration
:toc:[]

About this demo

.Exercises features including:
* ClusterPools
* ClusterSets

== Deployment

.**YMMV**
[TIP]
I use `kustomize build foo | oc apply -f -`, but you may wish to use `oc apply -k foo`.

=== Configure Credentials Secrets

* Update the values found in example secrets

[source,bash]
$ find . -name secrets -o -name certs
./kustomize/oauth/secrets
./kustomize/clusterdeployment/vsphere/secrets
./kustomize/clusterdeployment/vsphere/certs
./kustomize/clusterdeployment/azure/secrets
./kustomize/clusterdeployment/aws/secrets
./kustomize/clusterdeployment/base/secrets
./kustomize/clusterdeployment/base/certs

* Generate an htpasswd from the values found in link:kustomize/oauth/secrets/[kustomize/oauth/secrets/]

[source,bash]
----
$ cd kustomize/oauth/secrets
$ ../../../bin/mkhtpasswd
----

* Update vCenter password in vsphere example until <https://bugzilla.redhat.com/show_bug.cgi?id=1996188> resolves

[source,bash]
$ vi clusters/vsphere-demo/kustomize/clusterdeployment/install-config.yaml

=== Deploy Clusters

[source,bash]
----
$ kustomize build clusters/aws-demo/kustomize/clusterdeployment | oc apply -f -

$ kustomize build clusters/az-demo/kustomize/clusterdeployment | oc apply -f -

$ kustomize build clusters/vsphere-demo/kustomize/clusterdeployment | oc apply -f -
----

=== Deploy ClusterPools

[source,bash]
----
$ kustomize build clusterpools/aws-edge | oc apply -f -
$ kustomize build clusterpools/az-edge | oc apply -f -
----

== Demonstration

=== View ClusterPools

[source,bash]
----
$ oc get clusterpools aws-edge -n edge-pool 
$ oc get clusterpools az-edge -n edge-pool 
$ oc get namespaces | grep edge 

$ oc get namespaces -l hive.openshift.io/cluster-pool-name=aws-edge
$ oc get namespaces -l hive.openshift.io/cluster-pool-name=az-edge
----

=== Access Clusters

[source,bash]
----
$ oc get clusterdeployments -A
NAMESPACE          NAME               PLATFORM   REGION    CLUSTERTYPE   INSTALLED   INFRAID               VERSION   POWERSTATE    AGE
az-edge-cjl7n      az-edge-cjl7n      azure      westus2                 true        az-edge-cjl7n-hp5mw   4.8.4     Hibernating   45h
az-edge-t67sc      az-edge-t67sc      azure      westus2                 true        az-edge-t67sc-vdxcg   4.8.4     Hibernating   45h
demo-az-tofu-org   demo-az-tofu-org   azure      westus2                 true        demo-r4rhh            4.8.4     Hibernating   46h

$ ./bin/ext-kubeconfig demo-az-tofu-org
$ export KUBECONFIG=demo-az-tofu-org/auth/kubeconfig
$ oc describe console
----

* Configure htpasswd auth

[source,bash]
$ export KUBECONFIG=demo-az-tofu-org/auth/kubeconfig
$ kustomize build kustomization/oauth | oc apply -f -

=== Observability

.stringData for thanos config
[TIP]
We have to be roundabout thanks to thanos config coming from a file.
Let me know if you have a snazzy automation for this.

* Deploy obeservability

[source,bash]
kustomize build kustomize/observability | oc apply -f - 

* Configure Thanos with Object Bucket credentials 

[source,bash]
----
# update kustomize/observability/secretes/thanos-object-storage.yaml
vi kustomize/observability/secretes/thanos-object-storage.yaml 
oc apply -f kustomize/observability/secretes/thanos-object-storage.yaml
----

* Ensure firewall access from managed clusters to hub cluster at `observatorium-api-open-cluster-management-observability.apps.<cluster>.<domain>:443`

== Cleanup

=== Destroy Clusters

[source,bash]
----
kustomize build clusters/aws-demo/kustomize/clusterdeployment | oc delete -f -
kustomize build clusters/az-demo/kustomize/clusterdeployment | oc delete -f -

kustomize build clusters/vsphere-demo/kustomize/clusterdeployment | oc apply -f -
----

=== Destroy ClusterPools

[source,bash]
----
kustomize build clusterpools/aws-edge | oc delete -f -
kustomize build clusterpools/az-edge | oc delete -f -
----

== Status

.**Todo**
* Refactor out ./kustomize?
* Less setup and more demo

.**Bugs**
* https://bugzilla.redhat.com/show_bug.cgi?id=1995380
* https://bugzilla.redhat.com/show_bug.cgi?id=1996188

.**Tips**
* Unlike a ClusterDeployment, a ClusterPool does not directly enable the creation of a machinepool.