= Red Hat Advanced Cluster Management for Kubernetes Demonstration
:toc:[]

About this demo

.Exercises features including:
* ClusterDeployments
* ClusterPools
* ClusterSets
* <<Observability>>

== Deployment

.**YMMV**
[TIP]
In place of `kustomize build foo | oc apply -f -` you may use `oc apply -k foo`.

* Build a largish cluster
* Log in to it

=== Deploy ACM Hub

* Deploy ACM operator and MulticlusterHub resource.

[source,bash]
----
kustomize build hub | oc apply -f -
# first time will produce error below, so run twice:
# unable to recognize "STDIN": no matches for kind "MultiClusterHub" in version "operator.open-cluster-management.io/v1"
kustomize build hub | oc apply -f -
----

.Observability OBC TODO
[WARNING]
unable to recognize "STDIN": no matches for kind "DiscoveryConfig" in version "discovery.open-cluster-management.io/v1alpha1"
unable to recognize "STDIN": no matches for kind "ObjectBucketClaim" in version "objectbucket.io/v1alpha1"

=== Configure Credentials Secrets

* Update the values found in example secrets with your credentials.

[source,bash]
$ find . -name secrets -o -name certs
./credentials/vsphere/secrets
./credentials/vsphere/certs
./credentials/pull-secret/secrets
./credentials/azure/secrets
./credentials/ssh-keys/secrets
./credentials/aws/secrets
./credentials/gcp/secrets
./credentials/ocm/secrets
./credentials/base/secrets
./credentials/base/certs
./kustomize/oauth/secrets
./kustomize/observability/secrets # defer edits


* Update vCenter password (`.platform.vsphere.password`) in vsphere example until <https://bugzilla.redhat.com/show_bug.cgi?id=1996188> resolves

[source,bash]
$ vi clusters/vsphere-demo/install-config.yaml

=== Create Credentials for Cloud Providers

* Create credential secrets in open-cluster-management namespace.

[source,bash]
----
$ oc apply -k credentials/hub
----

.The following secrets are created.
[source,bash]
$ kustomize build credentials/hub | kfilt -k secret | grep ' name:'
  name: aws-creds
  name: azure-creds
  name: gcp-creds
  name: ocm-creds
  name: pull-secret
  name: ssh-private-key
  name: ssh-public-key
  name: vsphere-certs
  name: vsphere-creds

=== Deploy Clusters

* Deploy link:clusters/[clusters] to the desired clouds.

[source,bash]
----
$ kustomize build clusters/aws-demo     | oc apply -f -
$ kustomize build clusters/az-demo      | oc apply -f -
$ kustomize build clusters/vsphere-demo | oc apply -f -
----

:star: **Pro Tip** pipe `kustomize build` to `yq e . -` to preview before applying. Or skip both with `oc apply -k`

[source,bash]
----
$ oc apply -k clusters/gcp-demo

namespace/demo-gcp-tofu-org created
secret/gcp-creds created
secret/install-config created
secret/pull-secret created
secret/ssh-private-key created
secret/ssh-public-key created
klusterletaddonconfig.agent.open-cluster-management.io/demo-gcp-tofu-org created
managedcluster.cluster.open-cluster-management.io/demo-gcp-tofu-org created
clusterdeployment.hive.openshift.io/demo-gcp-tofu-org created
machinepool.hive.openshift.io/gcp-demo-worker created
----

==== Deploy EKS Cluster

Use script link:bin/mkeks[bin/mkeks] to deploy an EKS cluster.

=== Deploy ClusterPools

* Deploy link:clusterpools/[clusterpools] to the desired clouds.

[source,bash]
----
$ kustomize build clusterpools/aws-pool   | oc apply -f -
$ kustomize build clusterpools/azure-pool | oc apply -f -
----

==== Deploy Policies

* Deploy example Open Cluster Management link:policies/[policies].

[source,bash]
----
$ kustomize build apps/demo-acm-policies | oc apply -f -
----

== Demonstration

=== View ClusterPools

[source,bash]
----
$ oc get clusterpools aws-pool -n aws-pool
$ oc get clusterpools azure-pool -n azure-pool
$ oc get namespaces | grep pool

$ oc get namespaces -l hive.openshift.io/cluster-pool-name=aws-pool
$ oc get namespaces -l hive.openshift.io/cluster-pool-name=azure-pool
----

=== Access Clusters

[source,bash]
----
$ oc get clusterdeployments -A
NAMESPACE          NAME               PLATFORM   REGION    CLUSTERTYPE   INSTALLED   INFRAID               VERSION   POWERSTATE    AGE
az-edge-cjl7n      az-edge-cjl7n      azure      westus2                 true        az-edge-cjl7n-hp5mw   4.8.4     Hibernating   45h
az-edge-t67sc      az-edge-t67sc      azure      westus2                 true        az-edge-t67sc-vdxcg   4.8.4     Hibernating   45h
demo-az-tofu-org   demo-az-tofu-org   azure      westus2                 true        demo-r4rhh            4.8.4     Hibernating   46h

$ ./bin/ext-kubeconfig demo-az-tofu-org
$ export KUBECONFIG=demo-az-tofu-org/auth/kubeconfig
$ oc describe console
----

=== Htpasswd Authentication

* Generate random passwords and feed to an htpasswd file containing the values found in link:kustomize/oauth/secrets/[kustomize/oauth/secrets/]

[source,bash]
----
$ cd kustomize/oauth
$ touch secrets/passwords/$USER
# for each username in secrets/passwords inject a random password
# and build an htpasswd file
$ make
$ cat secrets/passwords/$USER
$ cat secrets/htpasswd
$ cd ../..
----

* Configure htpasswd auth. This will create the htpasswd secret. You must modify the `oauth/cluster` resource by hand. See link:kustomize/oauth/patch-oauth.yaml[]

[source,bash]
----
# log in to demo cluster
$ export KUBECONFIG=demo-az-tofu-org/auth/kubeconfig
# create htpasswd secret
$ kustomize build kustomize/oauth | oc apply -f -
# enable htpasswd authN
$ oc patch oauth/cluster --patch-file kustomize/oauth/patch-oauth.yaml --type=merge
----

=== Observability

Deploy RHACM https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html-single/observability/index[Observability Service]

* Extract the pull secret to be replicated into observability namespace

[source,bash]
$ oc extract secret/pull-secret -n openshift-config --to=kustomize/observability/secrets --confirm

* Deploy 

[source,bash]
$ kustomize build kustomize/observability | oc apply -f -

.**stringData for thanos config**
[IMPORTANT]
We have to be roundabout thanks to thanos config coming from stringdata.
Let me know if you have a snazzy automation for this. I guess this would work <https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-management/instance/observability/02-install-observability.yaml>

* Update Thanos Config Secret with Object Bucket credentials link:kustomize/observability/secrets/thanos-object-storage.yaml[]

[source,bash]
----
# update thanos config by following instructions in the dummy values
$ vi kustomize/observability/secrets/thanos-object-storage.yaml

# redeploy with updated secret
$ kustomize build kustomize/observability | oc apply -f -
----

* Ensure firewall access is permitted from managed clusters to the hub cluster at `observatorium-api-open-cluster-management-observability.apps.<cluster>.<domain>:443`

* Visit Grafana interface at `https://multicloud-console.apps.<cluster>.<domain>/grafana/` and see cluster metrics arrive within a few minutes.

==== Observability for EKS

OpenShift will "just work", but for EKS ACM must https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html[deploy the Kubernetes Metrics Server]. This now happens automatically.

== Install Demo Materials

* Install compliance operator, and setup auto scanning

[source,bash]
----
# do this twice:
$ oc apply -k 'https://github.com/redhat-cop/gitops-catalog/compliance-operator/aggregate/demo?ref=main'
----

Set policy-cis to enforcing

=== Deploy Sample Apps to EKS

[source,bash]
kustomize build apps/eks-sample | kubectl apply -f -

.Deploy to EKS:
* sample https://docs.aws.amazon.com/eks/latest/userguide/sample-deployment.html
* guestbook https://docs.aws.amazon.com/eks/latest/userguide/eks-guestbook.html
* k8s dashboard https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html

== Cleanup

=== Destroy Clusters

[source,bash]
----
$ kustomize build clusters/aws-demo | oc delete -f -
$ kustomize build clusters/az-demo  | oc delete -f -

$ kustomize build clusters/vsphere-demo | oc delete -f -
----

=== Destroy ClusterPools

[source,bash]
----
$ kustomize build clusterpools/aws-pool | oc delete -f -
$ kustomize build clusterpools/azure-pool  | oc delete -f -
----

== Status

.**Todo**
* Less setup and more demo

.**Bugs**
* https://bugzilla.redhat.com/show_bug.cgi?id=1995380
* https://bugzilla.redhat.com/show_bug.cgi?id=1996188

.**Tips**
* Unlike a ClusterDeployment, a ClusterPool does not directly enable the creation of a machinepool.
