= Red Hat Advanced Cluster Management for Kubernetes Demonstration
:toc:[]

About this demo

.Exercises features including:
* ClusterDeployments
* ClusterPools
* ClusterSets
* <<Observability>>

== Deployment

.**YMMV**
[TIP]
I use `kustomize build foo | oc apply -f -`, but you may wish to use `oc apply -k foo`.

=== Configure Credentials Secrets

* Update the values found in example secrets with your credentials.

[source,bash]
$ find . -name secrets -o -name certs
./credentials/vsphere/secrets
./credentials/vsphere/certs
./credentials/azure/secrets
./credentials/aws/secrets
./credentials/ocm/secrets
./credentials/base/secrets
./credentials/base/certs
./kustomize/oauth/secrets
./kustomize/observability/secrets # defer edits

* Generate random passwords and an htpasswd from the values found in link:kustomize/oauth/secrets/[kustomize/oauth/secrets/]

[source,bash]
----
$ cd kustomize/oauth/secrets
$ make
----

* Update vCenter password (`.platform.vsphere.password`) in vsphere example until <https://bugzilla.redhat.com/show_bug.cgi?id=1996188> resolves

[source,bash]
$ vi clusters/vsphere-demo/install-config.yaml

=== Create Credentials for Cloud Providers

[source,bash]
----
# kustomize build credentials/hub       | oc apply -f -
$ kustomize build credentials/aws       | oc apply -f -
$ kustomize build credentials/azure     | oc apply -f -
$ kustomize build credentials/ocm       | oc apply -f -
$ kustomize build credentials/vsphere   | oc apply -f -
----

=== Deploy Clusters

* Deploy cluster to desired cloud.
[source,bash]
----
$ kustomize build clusters/aws-demo     | oc apply -f -
$ kustomize build clusters/az-demo      | oc apply -f -
$ kustomize build clusters/vsphere-demo | oc apply -f -
----

==== Deploy EKS Cluster

Use script link:bin/mkeks[bin/mkeks] to deploy an EKS cluster.

=== Deploy ClusterPools

[source,bash]
----
$ kustomize build clusterpools/aws-pool   | oc apply -f -
$ kustomize build clusterpools/azure-pool | oc apply -f -
----

== Demonstration

=== View ClusterPools

[source,bash]
----
$ oc get clusterpools aws-pool -n aws-pool
$ oc get clusterpools azure-pool -n azure-pool
$ oc get namespaces | grep pool

$ oc get namespaces -l hive.openshift.io/cluster-pool-name=aws-pool
$ oc get namespaces -l hive.openshift.io/cluster-pool-name=azure-pool
----

=== Access Clusters

[source,bash]
----
$ oc get clusterdeployments -A
NAMESPACE          NAME               PLATFORM   REGION    CLUSTERTYPE   INSTALLED   INFRAID               VERSION   POWERSTATE    AGE
az-edge-cjl7n      az-edge-cjl7n      azure      westus2                 true        az-edge-cjl7n-hp5mw   4.8.4     Hibernating   45h
az-edge-t67sc      az-edge-t67sc      azure      westus2                 true        az-edge-t67sc-vdxcg   4.8.4     Hibernating   45h
demo-az-tofu-org   demo-az-tofu-org   azure      westus2                 true        demo-r4rhh            4.8.4     Hibernating   46h

$ ./bin/ext-kubeconfig demo-az-tofu-org
$ export KUBECONFIG=demo-az-tofu-org/auth/kubeconfig
$ oc describe console
----

* Configure htpasswd auth. This will create the htpasswd secret. You must modify the `oauth/cluster` resource by hand. See link:kustomize/oauth/patch-oauth.yaml[]

[source,bash]
$ export KUBECONFIG=demo-az-tofu-org/auth/kubeconfig
$ kustomize build kustomize/oauth | oc apply -f -

=== Observability

Deploy RHACM https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html-single/observability/index[Observability Service]

* Extract the pull secret to be replicated into observability namespace

[source,bash]
$ oc extract secret/pull-secret -n openshift-config --to=kustomize/observability/secrets --confirm

* Deploy 

[source,bash]
$ kustomize build kustomize/observability | oc apply -f -

.**stringData for thanos config**
[IMPORTANT]
We have to be roundabout thanks to thanos config coming from stringdata.
Let me know if you have a snazzy automation for this. I guess this would work <https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-management/instance/observability/02-install-observability.yaml>

* Update Thanos Config Secret with Object Bucket credentials link:kustomize/observability/secrets/thanos-object-storage.yaml[]

[source,bash]
----
# update thanos config by following instructions in the dummy values
$ vi kustomize/observability/secrets/thanos-object-storage.yaml

# redeploy with updated secret
$ kustomize build kustomize/observability | oc apply -f -
----

* Ensure firewall access is permitted from managed clusters to the hub cluster at `observatorium-api-open-cluster-management-observability.apps.<cluster>.<domain>:443`

* Visit Grafana interface at `https://multicloud-console.apps.<cluster>.<domain>/grafana/` and see cluster metrics arrive within a few minutes.

==== Observability for EKS

OpenShift will "just work", but for EKS you must https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html[deploy the Kubernetes Metrics Server] to EKS cluster

[source,bash]
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

== Install Demo Materials

* Install compliance operator, and setup auto scanning

[source,bash]
----
# do this twice:
$ oc apply -k 'https://github.com/redhat-cop/gitops-catalog/compliance-operator/aggregate/demo?ref=main'
----

Set policy-cis to enforcing

=== Deploy Sample Apps to EKS

[source,bash]
kustomize build apps/eks-sample | kubectl apply -f -

.Deploy to EKS:
* sample https://docs.aws.amazon.com/eks/latest/userguide/sample-deployment.html
* guestbook https://docs.aws.amazon.com/eks/latest/userguide/eks-guestbook.html
* k8s dashboard https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html

== Cleanup

=== Destroy Clusters

[source,bash]
----
$ kustomize build clusters/aws-demo | oc delete -f -
$ kustomize build clusters/az-demo  | oc delete -f -

$ kustomize build clusters/vsphere-demo | oc delete -f -
----

=== Destroy ClusterPools

[source,bash]
----
$ kustomize build clusterpools/aws-pool | oc delete -f -
$ kustomize build clusterpools/azure-pool  | oc delete -f -
----

== Status

.**Todo**
* Less setup and more demo

.**Bugs**
* https://bugzilla.redhat.com/show_bug.cgi?id=1995380
* https://bugzilla.redhat.com/show_bug.cgi?id=1996188

.**Tips**
* Unlike a ClusterDeployment, a ClusterPool does not directly enable the creation of a machinepool.
