---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: snoball-lab-bewley-net
spec:
  clusterName: snoball-lab-bewley-net
  clusterNamespace: snoball-lab-bewley-net
  clusterLabels:
    cloud: VSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true