---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snoball-lab-bewley-net

bases:
  - ../../credentials/base
  - ../../credentials/vsphere

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: install-config
    files:
      - install-config.yaml

resources:
  - namespace.yaml
  - managedcluster.yaml
  - clusterdeployment.yaml
  - klusterletaddonconfig.yaml
