apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: policy-gatekeeper-audit
spec:
  remediationAction: inform # will be overridden by remediationAction in parent policy
  severity: low
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: constraints.gatekeeper.sh/v1beta1
        kind: K8sRequiredLabels
        metadata:
          name: ns-must-have-gk
        status:
          totalViolations: 0

gcp$ kubectl get constraints ns-must-have-gk -o yaml | yq .status.violations -
- enforcementAction: dryrun
  kind: Namespace
  message: 'you must provide labels: {"gatekeeper"}'
  name: e2etestfail