---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: azure-pool

bases:
  - ../../credentials/azure

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: az-install-config
    files:
      - install-config.yaml

resources:
  - namespace.yaml
  - clusterpool.yaml
