---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: advanced-cluster-security-operator/instance/overlays/default
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acs-central
  name: acs-central-subscription
  namespace: stackrox
spec:
  channel: stackrox/acs-overlays-default
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-rule-acs-central
