# ClusterDeployment base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ssh-private-key
    files:
      - secrets/ssh-privatekey
  - name: pull-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - secrets/.dockerconfigjson
  - name: aws-creds
    envs:
      - secrets/.env.aws
  - name: azure-creds
    files:
      - secrets/osServicePrincipal.json
  - name: vsphere-creds
    envs:
      - secrets/.env.vsphere
  - name: vsphere-certs
    files:
      - certs/.cacert

# resources:
#- klusterletaddonconfig.yaml
#- clusterdeployment.yaml
#- machinepool.yaml
#- managedcluster.yaml
