---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- oauth.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: htpasswd
  namespace: openshift-config
  files:
    - secrets/htpasswd