---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-acs-securedcluster-helm

placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-policy-acs-securedcluster-helm

subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-acs-securedcluster-helm

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-acs-securedcluster-helm-sub

placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-policy-acs-securedcluster-helm-sub

subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-acs-securedcluster-helm-sub