= Policy ACS-SecuredCluster-Helm

== Description

Ensure that cluster is secured by ACS.
Installs Helm chart rather than Operator subscription.


.See also
* <https://docs.openshift.com/acs/3.72/installing/installing_helm/install-helm-customization.html>
* <https://github.com/stolostron/policy-collection/tree/main/policygenerator/policy-sets/community/openshift-plus>

.Effect
* Create a Channel on Hub for RHACS Helm charts 'https://mirror.openshift.com/pub/rhacs/charts/'
* Create a Subscription to install stackrox-secured-cluster-services Helm chart on managed cluster.
* Override Helm chart values with RHACS init bundle values.

.Remediation
* Enforce

.Scope
* vendor=EKS

Target is any platform that does lacks Operator Lifecycle Management.

== Requirements

Cluster init-bundle generated and resulting secrets stored in stackrox namespace:

* admission-control-tls
* collector-tls
* sensor-tls

You must generate the cluster init-bundle using the ACS Central web console and apply the results. See also: https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/instance/base/create-cluster-init-bundle-job.yaml

== Deploy

[source,bash]
----
cd policies/acs-securedcluster-helm
oc apply -k .
----

= Bugs and Known Issues

== Helm Release Name

The default release name 'stackrox-secured-cluster-services' is 34 characters. When installed by ACM that name will be truncated and get a random suffix to get the length to 32 characters.

This non-default name is blocked by the chart and prevents installation.

[source,]
FATAL ERROR:
You have chosen a release name of 'stackrox-secured-cluster--2c11b', not
'stackrox-secured-cluster-services'. We strongly recommend using the standard release name. If you

**Workaround**

The workaround for the moment is to set the `spec.packageOverrides.packageAlias` to a name at 32 characters or less (.i.e. _stackrox-secured-cluster-svcs_), and set `allowNonstandardReleaseName: true` in the packageOverrides, so the Chart will accept it.

[source,]
managed-cluster$ helm list -A
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                           APP VERSION
stackrox-secured-cluster-svcs   stackrox        1               2022-10-06 23:42:55.423977249 +0000 UTC deployed        stackrox-secured-cluster-services-72.0.0        3.72.0

== Pull Secret

Need to replicate pull secret to enable pulls from registry.redhat.io/advanced-cluster-security

== SecuredCluster Resource

Not yet verified because platform.stackrox.io API not yet stood up by the imagepullbackoff affected pods.
