= Policy ACS-SecuredCluster-Helm

== Description

Ensure that cluster is secured by ACS.
Installs Helm chart rather than Operator subscription.


.See also
* <https://docs.openshift.com/acs/3.72/installing/installing_helm/install-helm-customization.html>
* <https://github.com/stolostron/policy-collection/tree/main/policygenerator/policy-sets/community/openshift-plus>

.Effect
* Create a Channel on Hub for RHACS Helm charts 'https://mirror.openshift.com/pub/rhacs/charts/'
* Create a Subscription to install stackrox-secured-cluster-services Helm chart on managed cluster.
* Override Helm chart values with RHACS init bundle values.

.Remediation
* Enforce

.Scope
* vendor=EKS

Target is any platform that does lacks Operator Lifecycle Management.

== Requirements

Cluster init-bundle generated and resulting secrets stored in stackrox namespace:

* admission-control-tls
* collector-tls
* sensor-tls

You must generate the cluster init-bundle using the ACS Central web console and apply the results. See also: https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/instance/base/create-cluster-init-bundle-job.yaml

== Deploy

[source,bash]
----
cd policies/acs-securedcluster-helm
oc apply -k .
----

= Bugs and Known Issues

== Helm Release Name

The default release name 'stackrox-secured-cluster-services' is 34 characters. When installed by ACM that name will be truncated and get a random suffix to get the length to 32 characters.

This non-default name is blocked by the chart and prevents installation.

[source,]
FATAL ERROR:
You have chosen a release name of 'stackrox-secured-cluster--2c11b', not
'stackrox-secured-cluster-services'. We strongly recommend using the standard release name. If you

**Workaround**

The workaround for the moment is to set the `spec.packageOverrides.packageAlias` to a name at 32 characters or less (.i.e. _stackrox-secured-cluster-svcs_), and set `allowNonstandardReleaseName: true` in the packageOverrides, so the Chart will accept it.

[source,]
managed-cluster$ helm list -A
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                           APP VERSION
stackrox-secured-cluster-svcs   stackrox        1               2022-10-06 23:42:55.423977249 +0000 UTC deployed        stackrox-secured-cluster-services-72.0.0        3.72.0

== Missing CA Cert Bundle

OpenShift install uses a configmap labeled `config.openshift.io/inject-trusted-cabundle=true` to mount at `/etc/pki/injected-ca-trust/`, but admission-control on EKS fails to start with the folowing error.

[source,]
----
(⎈ |dbewley@redhat.com-zlsbc-admin@eks-demo.us-west-2.eksctl.io:stackrox) dale@bunny  ~  oc logs -f pod/admission-control-84ccdfdf96-fs7rp
No certificates found in /usr/local/share/ca-certificates
No certificates found in /etc/pki/injected-ca-trust
main: 2022/10/10 20:04:26.164958 main.go:40: Info: StackRox Sensor Admission Control Service, version 3.72.0
main: 2022/10/10 20:04:26.165255 certs.go:46: Error: Failed to load service certificate: {"code":1002,"message":"Failed to decode certificate"}
main: 2022/10/10 20:04:26.165283 certs.go:65: Info: No usable certificates found, attempting to fetch certificates from sensor ...
root logger: 2022/10/10 20:04:26.165494 logging.go:299: Error: Unexpected Error: invalid PEM
CA cert could not be decoded
github.com/stackrox/rox/pkg/mtls.readCA.func1
        github.com/stackrox/rox/pkg/mtls/crypto.go:161
        sync.(*Once).doSlow
                sync/once.go:68
...
main: 2022/10/10 20:04:26.165532 main.go:66: Error: Failed to configure certificates: failed to fetch certificates from sensor: failed to fetch certificates from sensor: failed to get service CA verifier: CA cert could not be decoded: invalid PEM. Connection to sensor might fail.
main: 2022/10/10 20:04:26.165589 main.go:73: Error: Could not establish a gRPC connection to Sensor: instantiating TLS config: client credentials: tls: failed to find any PEM data in certificate input. Some features, including recording violations generated by admission control, will not work.
pkg/grpc: 2022/10/10 20:04:26.216597 server.go:215: Info: Launching backend gRPC listener
pkg/grpc: 2022/10/10 20:04:26.217939 server.go:366: Panic: Failed to instantiate endpoint config of kind TLS-enabled HTTP: configuring TLS: tls conversion: tls: failed to find any PEM data in certificate input
panic: Failed to instantiate endpoint config of kind TLS-enabled HTTP: configuring TLS: tls conversion: tls: failed to find any PEM data in certificate input
----

== SecuredCluster Resource

Deployment not yet verified.
