= Policy ACS-SecuredCluster-Helm

== Description

Ensure that cluster is secured by ACS.
Installs Helm chart rather than Operator subscription.

See also <https://github.com/stolostron/policy-collection/tree/main/policygenerator/policy-sets/community/openshift-plus>

.Effect
* Create a Channel on Hub for RHACS Helm charts 'https://mirror.openshift.com/pub/rhacs/charts/'
* Create a Subscription to install stackrox-secured-cluster-services Helm chart on managed cluster.
* Override Helm chart values with RHACS init bundle values.

.Remediation
* Enforce

.Scope
* vendor=EKS

== Requirements

Cluster init-bundle generated and resulting secrets stored in stackrox namespace:

* admission-control-tls
* collector-tls
* sensor-tls

You must generate the cluster init-bundle using the ACS Central web console and apply the results. See also: https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/instance/base/create-cluster-init-bundle-job.yaml

== Deploy

[source,bash]
----
cd policies/acs-securedcluster-helm
oc apply -k .
----

= Bugs

The helm release is installed with a randomize name which changes if the subscription is recreated. This non-default name is blocked by the chart and prevents installation.

[source,]
FATAL ERROR:
You have chosen a release name of 'stackrox-secured-cluster--2c11b', not
'stackrox-secured-cluster-services'. We strongly recommend using the standard release name. If you

The workaround for the moment is to set `allowNonstandardReleaseName: true` in packageOverrides. But what is the fix?

[source,]
managed-cluster$ helm list -A
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                           APP VERSION
apache                          helloworld-helm 1               2022-10-06 19:47:52.524616989 +0000 UTC deployed        apache-9.2.4                                    2.4.54
stackrox-secured-cluster--2c11b stackrox        1               2022-10-06 22:12:56.758330486 +0000 UTC deployed        stackrox-secured-cluster-services-72.0.0        3.72.0
