---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

generatorOptions:
  disableNameSuffixHash: true
  labels:
    cluster.open-cluster-management.io/type: rhocm

secretGenerator:
  - name: ocm-creds
    files:
      - secrets/ocmAPIToken
