---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    cluster.open-cluster-management.io/credentials: ""
    cluster.open-cluster-management.io/type: vmw

secretGenerator:
  - name: vsphere-creds
    envs:
      - secrets/.env.vsphere
  - name: vsphere-certs
    files:
      - certs/.cacert
