---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: demo-gcp-tofu-org-worker
spec:
  clusterDeploymentRef:
    name: demo-gcp-tofu-org
  name: worker
  platform:
    gcp:
      type: n1-standard-4
  replicas: 3