apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: rhacs-central-policies

policyDefaults:
  namespace: open-cluster-management-policies
  remediationAction: enforce
  severity: high
  categories: 
    - CM Configuration Management
    - TofuOrg Baseline
  
  placement:
    clusterSelectors:
      local-cluster: "true"

policies:
  - name: policy-acs-operator
    manifests:
      - path: manifests