---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: tbd
  labels:
    cloud: vSphere
    vendor: OpenShift
spec:
  baseDomain: lab.bewley.net
  clusterName: tbd
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 2
  installed: false
  platform:
    vsphere:
      cluster: Goat
      certificatesSecretRef:
        name: vsphere-certs
      credentialsSecretRef:
        name: vsphere-creds
      vCenter: vcenter.lab.bewley.net
      datacenter: Garden
      defaultDatastore: VMData-HD
      network: lab-192-168-4-0-b24
  provisioning:
    installConfigSecretRef:
      name: install-config
    sshPrivateKeySecretRef:
      name: ssh-private-key
    imageSetRef: # see ClusterImageSets
      name: img4.10.5-x86-64-appsub
  pullSecretRef:
    name: pull-secret
