---
# https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/observability
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-observability

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: multiclusterhub-operator-pull-secret
    type: kubernetes.io/dockerconfigjson
    files:
      # oc extract secret/pull-secret -n openshift-config --to=secrets --confirm
      - secrets/.dockerconfigjson

resources:
  - namespace.yaml
  - objectbucketclaim.yaml
  - multiclusterobservability.yaml
  - secrets/thanos-object-storage.yaml

patchesStrategicMerge:
  - patches/multiclusterobservability.yaml
