---
# https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html/observability
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-observability

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: multiclusterhub-operator-pull-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - secrets/.dockerconfigjson

resources:
  - namespace.yaml
  - objectbucketclaim.yaml
  - multiclusterobservability.yaml

patchesStrategicMerge:
  - patches/multiclusterobservability.yaml
