---
# https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.8/html/managing_hybrid_and_multicloud_resources/object-bucket-claim
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  # intentionally not 'thanos-object-storage'. See secrets/
  name: thanos-storage
spec:
  generateBucketName: rhacm-thanos
  storageClassName: openshift-storage.noobaa.io
