---
apiVersion: hive.openshift.io/v1
kind: ClusterPool
metadata:
  name: aws-pool
  labels:
    cluster.open-cluster-management.io/clusterset: qa-cs
    cloud: AWS
    region: us-west-2
    vendor: OpenShift
spec:
  baseDomain: aws.tofu.org
  imageSetRef:
    name: img4.10.22-x86-64-appsub
  # do not create worker machinepool
  skipMachinePools: true
  installConfigSecretTemplateRef:
    name: aws-install-config
  platform:
    aws:
      credentialsSecretRef:
        name: aws-creds
      region: us-west-2
  pullSecretRef:
    name: pull-secret
  size: 2
