---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aws-pool

bases:
  - ../../credentials/aws

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: aws-install-config
    files:
      - install-config.yaml

resources:
  - namespace.yaml
  - clusterpool.yaml
