---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      kind: Job
      name: storage-cluster-label-worker-nodes
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value: [{name: selector, value: node-role.kubernetes.io/infra}]
