apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Azure
    name: demo-az-tofu-org
    vendor: OpenShift
    location: cloud
    usage: production
  name: demo-az-tofu-org
spec:
  hubAcceptsClient: true
