---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edge-pool

bases:
  # cloud provider and pull secrets
  - ../../kustomize/clusterdeployment/azure

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: az-install-config
    files:
      - install-config.yaml

resources:
  - namespace.yaml
  - clusterpool.yaml
