---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

generatorOptions:
  disableNameSuffixHash: true
  labels: 
    cluster.open-cluster-management.io/credentials: ""
    cluster.open-cluster-management.io/type: azr

bases:
  - ../base

secretGenerator:
  - name: azure-creds
    files:
      - secrets/osServicePrincipal.json
      - secrets/baseDomain
      - secrets/baseDomainResourceGroupName
      - secrets/cloudName
      # - secrets/ssh-privatekey
      # - secrets/ssh-publickey
