---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

generatorOptions:
  disableNameSuffixHash: true

bases:
  - ../base

secretGenerator:
  - name: aws-creds
    envs:
      - secrets/.env.aws
