---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: demo-acm-policies
  name: demo-acm-policies-app
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - demo-acm-policies
