---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: policies
    apps.open-cluster-management.io/git-path: policies
  labels:
    app: demo-acm-policies
    app.kubernetes.io/part-of: demo-acm-policies
    apps.open-cluster-management.io/reconcile-rate: medium
    apps.open-cluster-management.io/reconcile-option: merge
  name: demo-acm-policies-sub
spec:
  channel: policies/demo-acm-policies-chan
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-acm-policies-placement

