= Secured Cluster Policies

For OLM environments

== Policy ACS-SecuredCluster

=== Description

Ensure that cluster is secured by RHACS.

See also <https://github.com/stolostron/policy-collection/tree/main/policygenerator/policy-sets/community/openshift-plus>

.Effect
* Create SecuredCluster resource on managed clusters with proper endpoint and TLS secrets from Stackrox cluster init bundle on hub cluster.

.Remediation
* Enforce

.Scope
* vendor=[EKS,GKE,OpenShift]

=== Requirements

Cluster init-bundle generated and resulting secrets stored in stackrox namespace:

* admission-control-tls
* collector-tls
* sensor-tls

You must generate the cluster init-bundle using the ACS Central web console and apply the results. See also: https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/instance/base/create-cluster-init-bundle-job.yaml

=== Known Issues and Bugs

Needs further validation for xKS

== Policy ACS-SecuredCluster-Secrets

=== Description

Ensure cluster init bundle contents are propegated to secured clusters.

Non-OLM, xKS clusters will recieve secrets via Helm values. See link:../acs-securedcluster-helm[acs-securedcluster-helm policy].

.Effect
* Create TLS secrets on managed clusters Stackrox cluster init bundle on hub cluster.

.Remediation
* Enforce

.Scope
* vendor=OpenShift (not local-cluster)

=== Requirements

Cluster init-bundle pre-generated, and resulting secrets stored in stackrox namespace:

* admission-control-tls
* collector-tls
* sensor-tls

You must generate the cluster init-bundle using the RHACS Central web console and apply the results. See also: https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/instance/base/create-cluster-init-bundle-job.yaml

== Deploy

Requires https://github.com/stolostron/policy-generator-plugin Kustomize plugin

[source,bash]
----
cd policies/acs-securedcluster
kustomize build --enable-alpha-plugins . | oc apply -f -
oc get securedcluster -n stackrox
----

=== Known Issues and Bugs

Needs further validation for xKS
