---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ssh-private-key
    files:
      - secrets/ssh-privatekey

  - name: ssh-public-key
    files:
      - secrets/ssh-publickey
