---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: 'demo-az-tofu-org'
  namespace: 'demo-az-tofu-org'
  labels:
    cloud: 'Azure'
    vendor: 'OpenShift'
spec:
  baseDomain: az.tofu.org
  clusterName: 'demo'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 2
  installed: false
  platform:
    azure:
      baseDomainResourceGroupName: ocp
      credentialsSecretRef:
        name: azure-creds
      region: westus2
  provisioning:
    installConfigSecretRef:
      name: install-config
    sshPrivateKeySecretRef:
      name: ssh-private-key
    imageSetRef:
      name: img4.8.4-x86-64-appsub
  pullSecretRef:
    name: pull-secret
