---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: demo-az-tofu-org-worker
  namespace: demo-az-tofu-org
spec:
  clusterDeploymentRef:
    name: demo-az-tofu-org
  name: worker
  platform:
    azure:
      type: Standard_D2s_v3
      osDisk:
        diskSizeGB: 100
      zones: 
      - "1"
      - "2"
      - "3"
  replicas: 3
