---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      # need CA for OCS, to fix this
      insecure: true

      # replace with "oc get noobaa -n openshift-storage -o json | jq -r '.items[0].status.services.serviceS3.internalDNS[0]' |awk -F/ '{print $3}' | cut -d: -f 1"
      endpoint: s3.openshift-storage.svc

      bucket: "replace with oc get obc/thanos-storage -n open-cluster-management-observability -o jsonpath='{.spec.bucketName}'"

      access_key: "replace with oc extract -n open-cluster-management-observability secret/thanos-storage --keys AWS_ACCESS_KEY_ID --to=-"

      secret_key: "replace with oc extract -n open-cluster-management-observability secret/thanos-storage --keys AWS_SECRET_ACCESS_KEY --to=-"