---
apiVersion: v1
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox
  annotations:
    init-bundle.stackrox.io/id: ''
    init-bundle.stackrox.io/name: local-cluster
type: Opaque
data:
  ca.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "ca.pem") hub}}
  admission-control-cert.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-cert.pem") hub}}
  admission-control-key.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-key.pem") hub}}
