---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# not usable until ssh keys refactored out of base or base refactored out of each cloud cred

namespace: open-cluster-management

bases:
  - ../base
  - ../aws
  - ../azure
  - ../ocm
  - ../vsphere
