---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# populate ACM hub with credentials for all cloud providers

namespace: open-cluster-management

bases:
  - ../base
  - ../aws
  - ../azure
  - ../ocm
  - ../vsphere
