apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acs-central
  namespace: 
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - acs-central
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: app-acs
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: acs-overlays-default
  namespace: app-acs
spec:
  type: Git
  pathname: 'https://github.com/redhat-cop/gitops-catalog.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: advanced-cluster-security-operator/instance/overlays/default
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acs-central
  name: acs-central-subscription
  namespace: 
spec:
  channel: app-acs/acs-overlays-default
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-policy-acs-operator
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: acs
  name: placement-policy-acs-operator
  namespace: 
spec:
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - infra
