---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: demo-aws-tofu-org
  labels:
    cloud: 'AWS'
    region: 'us-west-1'
    vendor: 'OpenShift'
    usage: development
    environment: infra
    customer: 'Tofu.org'
spec:
  baseDomain: aws.tofu.org
  clusterName: 'demo2'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 2
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: aws-creds
      region: us-west-1
  provisioning:
    installConfigSecretRef:
      name: install-config
    sshPrivateKeySecretRef:
      name: ssh-private-key
    imageSetRef:
      name: img4.13.15-x86-64-appsub
  pullSecretRef:
    name: pull-secret
