---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-aws-tofu-org

bases:
  - ../../credentials/base
  - ../../credentials/aws

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: install-config
    files:
      - install-config.yaml

resources:
  - namespace.yaml
  - managedcluster.yaml
  - managedclusterset.yaml
  - clusterdeployment.yaml
  - machinepool.yaml
  - klusterletaddonconfig.yaml
