---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: 'demo-lab-bewley-net'
spec:
  clusterName: 'demo-lab-bewley-net'
  clusterNamespace: 'demo-lab-bewley-net'
  clusterLabels:
    cloud: VSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true