---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-lab-bewley-net

bases:
  - ../../credentials/base
  - ../../credentials/vsphere

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: install-config
    files:
      - install-config.yaml

configMapGenerator:
  - name: manifests
    files:
    - manifests/99-worker-registry-proxy.yaml
    # - manifests/99-master-registry-proxy.yaml

resources:
  - namespace.yaml
  - managedcluster.yaml
  - clusterdeployment.yaml
  - machinepool.yaml
  - klusterletaddonconfig.yaml
